######################
# Threads to use
######################
THREADS: 5

######################
# Database information
######################
DATABASE:
    type: 'postgres'
    mysql:
        user: 'bravo'
        password: 'bravo'
        host: '127.0.0.1'
        database: 'bravo'
        port: 3306
        pool_size: 10
        pool_name: 'bravo'
    postgres:
        user: 'bravo'
        password: 'bravo'
        host: 'localhost'
        port: 5432
        database: 'bravo'
    sqlite:
        name: 'bravo'
